{...}:
{
  imports = [
    ./autogenerated_hardware.nix
    ./boot.nix
    ./fonts.nix
    ./hardware.nix
    ./packages.nix
    ./services.nix
    ./starship.nix
    ./network.nix
    ./nvidia.nix
    ./system.nix
    ./users.nix
    ./xdg.nix
  ];
}
